### ISSUE TITLE
No CreateAssetBundle.cs?

### ISSUE THREAD

**Issue by hearth1an** [ow-mods/outer-wilds-unity-template#2]
![image](https://user-images.githubusercontent.com/106444732/229364544-816949ff-f021-463c-98df-3d90f4e626ad.png)

**Comment by xen-42** [comment]
Use the asset bundle browser tool that is now included with it.

![image](https://user-images.githubusercontent.com/22628069/229367443-3d2ab31a-8489-4c1e-944b-cf2dbfeaae85.png)

Then to build you click the build tab in the popup and you click build after configuring the folder and what stuff is included in the bundle.
